# Generated by Django 2.2.2 on 2019-06-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190620_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
