# Generated by Django 2.2.2 on 2019-06-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDafiti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=20)),
                ('quantidade', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=20)),
                ('estoque_valor', models.CharField(max_length=20)),
            ],
        ),
    ]
