# Generated by Django 2.2.2 on 2019-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testdafiti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdafiti',
            name='estoque_valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='testdafiti',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testdafiti',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
