# Generated by Django 2.2.2 on 2019-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190620_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdafiti',
            name='estoque_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='testdafiti',
            unique_together={('produto',)},
        ),
    ]
