# Generated by Django 2.2.2 on 2019-06-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190620_1724'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testdafiti',
            unique_together=set(),
        ),
    ]
