# Generated by Django 2.2.2 on 2019-06-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190620_1736'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testdafiti',
            unique_together={('produto', 'quantidade')},
        ),
    ]
