# Generated by Django 2.2.2 on 2019-06-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190620_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdafiti',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='testdafiti',
            unique_together={('product_id', 'produto', 'quantidade')},
        ),
    ]
