# Generated by Django 2.2 on 2019-06-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20190514_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('Setar NF-e', 'Usuario pode setar NF-e'), ('Permissão 2', 'Permissão 2'), ('Permissão 3', 'Permissão 3'))},
        ),
    ]
