# Generated by Django 2.2 on 2019-06-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20190615_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuario pode setar NF-e'), ('ver_dashboard', 'Pode visualizar dashboard'))},
        ),
    ]
