# Generated by Django 2.2.2 on 2019-06-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0006_auto_20190615_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdopedido',
            options={'verbose_name': 'Item do pedido', 'verbose_name_plural': 'Itens do pedido'},
        ),
        migrations.AlterUniqueTogether(
            name='itemdopedido',
            unique_together={('venda', 'produto')},
        ),
    ]
