# Generated by Django 2.2 on 2019-04-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20190422_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=50)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=50)),
                ('impostos', models.DecimalField(decimal_places=2, max_digits=50)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Person')),
            ],
        ),
    ]
