# Generated by Django 2.2 on 2019-06-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20190513_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'DELETAR CLIENTES'),), 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
