# Generated by Django 2.2.2 on 2019-06-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20190615_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'telefone')},
        ),
    ]
