# Generated by Django 2.2.2 on 2019-06-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20190617_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'DELETAR CLIENTES'),), 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
