# Generated by Django 2.2.3 on 2019-07-30 07:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_auto_20190617_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
    ]
