# Generated by Django 2.2.3 on 2019-08-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
